_format_version: "1.1"
services:
- connect_timeout: 60000
  host: grpcb.in
  name: grpcbin-service
  port: 9000
  protocol: grpc
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - headers:
      x-grpc:
      - "true"
    name: grpcbin-get-route
    methods:
    - GET
    paths:
    - /
    path_handling: v0
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
    plugins:
    - name: grpc-gateway
      config:
        proto: /usr/local/kong/hello-gateway.proto
      enabled: true
      protocols:
      - grpc
      - grpcs
      - http
      - https
