version: "3.8"

networks:
  kongnet:
    driver: bridge

services:
  
  loss:
    hostname: loss
    image: agilbert93/air-loss-poc
    networks:
    - kongnet
    ports:
    - 443:443
    - 80:80
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
    healthcheck:
      test: ["CMD", "echo 1"]
    
      
  address:
    hostname: address
    image: agilbert93/address-service
    networks:
    - kongnet
    ports:
    - 7777:7777
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
    healthcheck:
      test: ["CMD", "echo 1"]
        
  # #DB for Kong
  # kong-database:
  #   hostname: kong-database
  #   image: postgres:9.6
  #   networks:
  #   - kongnet
  #   environment:
  #     POSTGRES_USER: kong
  #     POSTGRES_DB: kong
  #     POSTGRES_PASSWORD: kong
  #   ports:
  #   - 5432:5432
  
  #Kong Gateway
  kong:
    hostname: kong
    image: agilbert93/kong-air-poc
    networks: 
    - kongnet
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
    ports:
      - 8000:8000
      #- 8001:8001
      - 9080:9080
      #- 8443:8443
      #- 8444:8444    
      #- 9000:9000
      #- 9443:9443
    environment:
      #KONG_PREFIX: /usr/local/kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000 reuseport, 0.0.0.0:8443 ssl reuseport, 0.0.0.0:9080 http2 reuseport, 0.0.0.0:9443 http2 ssl backlog=16384
      #KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/config.yml
      #KONG_PROXY_ERROR_LOG: /dev/stdout
      KONG_DATABASE: 'off' #'postgres'
      #KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      #KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      #KONG_LUA_PACKAGE_PATH: /usr/local/custom/?.lua;;
      #KONG_CUSTOM_PLUGINS: grpc-gateway
      #KONG_PLUGINS: grpc-gateway
      KONG_LOG_LEVEL: debug
    healthcheck:
      test: ["CMD", "echo 1"]
    #links:
    #- kong-database:kong-database
    #depends_on:
    #- kong-database
    #- kong-setup

  # #Kong Gateway
  # kong-setup:
  #   image: agilbert93/kong-db-air-poc
  #   networks: 
  #   - kongnet
  #   restart: on-failure  
  #   environment:
  #     KONG_PROXY_LISTEN: 0.0.0.0:8000 reuseport, 0.0.0.0:8443 backlog=16384 reuseport ssl http2, 0.0.0.0:9443 http2 ssl
  #     KONG_DECLARATIVE_CONFIG: /etc/kong/config.yml
  #     KONG_DATABASE: 'postgres'
  #     KONG_PG_HOST: kong-database
  #     KONG_PG_USER: kong
  #     KONG_PG_PASSWORD: kong
  #     KONG_CASSANDRA_CONTACT_POINTS: kong-database
  #     KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
  #     KONG_LUA_PACKAGE_PATH: /usr/local/custom/?.lua;;
  #     KONG_PLUGINS: grpc-gateway
  #     KONG_LOG_LEVEL: debug
  #   #links:
  #   #- kong-database:kong-database
  #   depends_on:
  #   - kong-database

# Dashboard
  # konga:
  #   image: pantsel/konga:next
  #   restart: always
  #   networks:
  #   - kongnet
  #   environment:     
  #     DB_HOST: kong-database
  #     DB_PORT: 5432
  #     DB_USER: kong
  #     DB_PASSWORD: kong
  #     TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
  #     NODE_ENV: development
  #     NO_AUTH: "true"
  #   depends_on:
  #   - kong-database
  #   links:
  #   - kong:kong
  #   - kong-database:kong-databse
  #   ports:
  #   - "1337:1337"

